version: '2'
services:
  jekyll:
    image: jekyll/jekyll@sha256:d1bf33637d476e3cb2d5858038673cc93bc961e9390d31171d9febde5c5d24fd
    command: jekyll build --watch
    tty: true
    volumes:
        - ./app:/srv/jekyll
        - ./build:/srv/build
        - ./bundle:/usr/local/bundle:delegated
  server:
    image: nginx:1.14.2
    ports:
        - "127.0.0.1:8080:8080"
    volumes:
        - ./build:/usr/share/nginx/html
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/logs:/var/log/nginx
